version: '3'
services:
  web:
    command: >
      bash -c "
        npm i &&
        bundle install &&
        rails db:migrate &&
        bundle exec whenever --update-crontab &&
        rails s -p 3000 -b '0.0.0.0'
      "
    ports:
      - "3000:3000"


