version: '3'
services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: pgface
      TZ: Asia/Tokyo
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      bash -c "
        npm i &&
        bundle install &&
        rails db:migrate &&
        bundle exec whenever --update-crontab &&
        rails s -p 3000 -b '0.0.0.0'
      "
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/share_bike
      - bundle-path:/usr/local/bundle:cached
    ports:
      - "3000:3000"
    links:
      - db

volumes: 
  # cache the bundle
  bundle-path:
  postgres-data: