version: '3'
services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: pgface
      TZ: Asia/Tokyo
    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/share_bike
      - bundle-path:/usr/local/bundle:cached
    links:
      - db

volumes:
  # cache the bundle
  bundle-path:

