version: '3'
services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: sb-https-portal
    ports:
      - '80:80'
      - '443:443'
    restart: always
    links:
      - web
      - ghost
    environment:
      DOMAINS: '
        sharebiker:beforetest@sharebiker.net -> http://web:3000,
        cms.sharebiker.net -> http://ghost:2368
      '
      STAGE: 'production' #PRO
      CLIENT_MAX_BODY_SIZE: 10M
    volumes:
      - sb-ssl-certs:/var/lib/https-portal
      - ./data/static:/var/www/vhosts

  web:
    build: .
    environment:
      TZ: Asia/Tokyo
    volumes:
      - .:/share_bike
      - bundle-path:/usr/local/bundle:cached
    links:
      - db
    command: >
      bash -c "
        npm i &&
        bundle install &&
        bundle exec rake assets:precompile RAILS_ENV=production &&
        rails db:migrate RAILS_ENV=production &&
        bundle exec whenever --update-crontab &&
        rails s -p 3000 -b '0.0.0.0' -e production
      "

  ghost:
    image: ghost
    environment:
      url: https://cms.sharebiker.net
    volumes:
      - ./data/ghost:/var/lib/ghost/content

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pgface
      TZ: Asia/Tokyo
    volumes:
      - ./data/postgre:/var/lib/postgresql/data

volumes:
  sb-ssl-certs:
  bundle-path:


